[JBTM-3406] test that different node name is not recovered in XTS inbound txbridge recovery module
jbosstm/narayana pull request #1771
Opened 2021-01-28 11:56 UTC by ochaloup

A test for https://issues.redhat.com/browse/JBTM-3406

The master PR: https://github.com/jbosstm/narayana/pull/1768

!QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO !LRA
XTS MAIN

2021-02-03 11:59 UTC, mmusgrov submitted a review, later dismissed

2021-02-03 16:45 UTC, tomjenkinson requested changes
The PR appears to hang XTS: http://narayanaci1.eng.hst.ams2.redhat.com/job/btny-pulls-narayana-417/PROFILE=XTS,jdk=jdk7.latest,label=linux/14/

2021-02-05 12:42 UTC, ochaloup commented
@mmusgrov @tomjenkinson with JDK7 and byteman compatibility I needed to stay with version 2.x. With some changes the test is working now. Could you please re-review?

2021-02-05 13:02 UTC, tomjenkinson approved these changes

2021-02-08 12:26 UTC, merged