JBTM-3437 JMS 2.0 integration
jbosstm/narayana pull request #1793
Opened 2021-02-27 15:39 UTC by mmusgrov

https://issues.redhat.com/browse/JBTM-3437

MAIN CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA !NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle

2021-02-28 12:40 UTC, zhfeng requested changes

2021-02-28 12:40 UTC, zhfeng commented on ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/ConnectionProxy.java
> +        return xaConnection.createSession(sessionMode);
It should check the JTA transaction is active and register the XAResource just like the above method
```
createSession(boolean trasacted, int acknowledgeMode);
```

2021-02-28 12:40 UTC, zhfeng commented on ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/ConnectionProxy.java
> +        return xaConnection.createSession();
Same here.

2021-02-28 12:40 UTC, zhfeng commented on ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/ConnectionFactoryProxy.java
> +    }
I think we have to register the XAResource just like we do in ```ConnectionProxy```

```
XAJMSContext xaContext = xaConnectionFactory.createXAContext();
JMSContext context = new JMSContextProxy(xaContext, transactionHelper);
if (checkJTATransactionIsActive) {
     regiterXAResource(xaContext.getXAResource();
}
return context;
```

Also I think we need to provide ```JMSContextProxy``` to wrap ```JMSContext``` which delist the XAResource in ```close()``` method just like ```SessionProxy```.

2021-02-28 12:40 UTC, zhfeng commented on ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/ConnectionFactoryProxy.java
> +        return xaConnectionFactory.createXAContext(userName, password);
Same as above.

2021-02-28 12:40 UTC, zhfeng commented on ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/ConnectionFactoryProxy.java
> +        return xaConnectionFactory.createXAContext(userName, password).createContext(sessionMode);
Same as above.

2021-02-28 12:40 UTC, zhfeng commented on ArjunaJTA/jms/src/main/java/org/jboss/narayana/jta/jms/ConnectionFactoryProxy.java
> +        return xaConnectionFactory.createXAContext().createContext(sessionMode);
Same as above.

2021-02-28 12:43 UTC, zhfeng commented
Thanks @mmusgrov for working on this enhancement and I think it could be better if we can add some unit tests for the JMS 2.0

2021-03-02 13:55 UTC, gytis commented
I second @zhfeng here. I think that both session and context should be enlisted and delisted in the new methods. For the JMSContext we'll need a new proxy class to handle the delisting.

2021-04-08 12:47 UTC, mmusgrov commented
I've put the PR on hold while I do the integration tests.

2021-07-01 14:58 UTC, zhfeng commented
@mmusgrov is there any update ?

2022-01-31 09:48 UTC, mmusgrov commented
@zhfeng (and t-ice and hhoffstaette) will you indicate what the impact of not having JMS 2.0 integration is for you? Once we know that then we can schedule some resources to do the work. Alternatively, since this is an open source community project we do accept pull requests from the community.

2022-06-10 11:23 UTC, tomjenkinson commented
@mmusgrov IIUC JMS 2.0 seems to be related to a possible approach to adding support into Quarkus for JMS and transactions https://github.com/quarkusio/quarkus/issues/14871 /cc @zhfeng

2022-06-13 09:05 UTC, closed without merging

2022-06-13 09:06 UTC, mmusgrov commented
closed in favour of #1979