Adding version and license badge to readme file
jbosstm/narayana pull request #1804
Opened 2021-03-22 17:30 UTC by mayankkunwar

This is just a minor enhancement in *readme* file to add a project version and license badge which would point to maven repository and LGPL license page respectively.

Since the change is only in readme file, hence triggering a CI build would not be necessary.
!MAIN !CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !BLACKTIE !PERF !LRA !NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle

2021-03-23 09:36 UTC, ochaloup approved these changes

2021-03-23 09:46 UTC, mmusgrov requested changes
There is no explanation or justification for why we need this change.
We already have a LICENSE file.
What is the relationship between the LICENSE and the README.md?
Now we are referring to the license from multiple places (at least three references), do we want this amount of duplication.

2021-03-23 09:58 UTC, ochaloup commented
I like the idea and I think the duplication is good for the license.

2021-03-23 10:01 UTC, mmusgrov commented
Yes but there is zero justification on the PR. It might look nice but why do we want it?

2021-03-23 10:01 UTC, mayankkunwar commented
These badges would be a quick info to the Narayana users/contributors or new comer to the repository. As whosever visit to any repository in git tries to have a quick look into the readme of that project. 

The eye catchy badges would be give quick and important piece of information about our project without digging into files for the info. 

If you say this badge is not required, I would remove it or if you want me to add more badges for displaying other information, will add them as part of this PR.

2021-03-23 10:03 UTC, mmusgrov commented
I don't like the badges so I will remove my review.

2021-03-23 10:34 UTC, mayankkunwar commented
Okay I have added more description to the PR and removed the LICENSE badge

2021-03-23 10:49 UTC, jmfinelli commented
TBH, I like badges and I think that having something similar to [quarkus](https://github.com/quarkusio/quarkus) might help newcomers (but also old committers) to immediately get important info about Narayana (e.g. current version and compatible JDKs)

2021-03-23 11:53 UTC, mmusgrov commented
> Okay I have added more description to the PR and removed the LICENSE badge

Don't remove them just because I said I didn't like the badges. If people want them then, since this is a community effort, no individual should be able to overrule a majority preference without good reason.

2021-03-25 07:29 UTC, mayankkunwar commented
Okay Mike, I thought this discussion should be unanimous. But if the case of majority then I will push these changes. Thanks

2021-03-25 07:30 UTC, merged