[SCRIPTS ONLY] making LRA test build faster
jbosstm/narayana pull request #1807
Opened 2021-03-26 15:03 UTC by ochaloup

* not building WildFly on LRA testing
* not building all Narayana artifacts when need to run only LRA testing
* shrinking a bit number of dependencies to download less

LRA
!MAIN !CORE !QA_JTA !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !QA_JTS_JACORB !BLACKTIE !XTS !PERF NO_WIN !RTS !AS_TESTS !TOMCAT !JACOCO

2021-03-26 17:18 UTC, mmusgrov commented
@ochaloup When I execute the command `PROFILE=LRA ./scripts/hudson/narayana.sh` with your PR I get the following error building the "LRA tests: Basic" module:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:3.1.0:jar (default-jar) on project lra-test-basic: You have to use a classifier to attach supplemental artifacts to the project instead of replacing them.

Any ideas about what I am missing.

2021-03-26 18:03 UTC, mmusgrov requested changes
Your latest commit resolved my issue.

2021-03-26 18:15 UTC, ochaloup commented on scripts/hudson/narayana.sh
> +  unzip -q artifacts.zip
sure, I added `-o` for the `unzip` command

2021-03-29 08:09 UTC, mmusgrov approved these changes

2021-03-29 08:09 UTC, merged