[JBTM-3424] Make consistency in error messag printed in log and retur…
jbosstm/narayana pull request #1859
Opened 2021-06-21 11:38 UTC by moulalis

https://issues.redhat.com/browse/JBTM-3424

MAIN CORE TOMCAT AS_TESTS RTS JACOCO XTS QA_JTA QA_JTS_JACORB QA_JTS_JDKORB QA_JTS_OPENJDKORB BLACKTIE PERF LRA !NO_WIN DB_TESTS mysql db2 postgres oracle

2021-06-21 11:47 UTC, moulalis commented
TESTIT

2021-06-21 13:14 UTC, ochaloup commented
TESTIT

2021-06-21 13:34 UTC, ochaloup commented
Hello @moulalis.

Thank you for submitting you pull request and providing the fix. We appreciate it.
The fix starts with the good end but it does not cover the whole range of https://issues.redhat.com/browse/JBTM-3424. The snippet which is placed in the issue description is only an example how the code looks like. It does not mean that's the only place in our code where we consider the deficiency that the jira talks about. The point of the issue is to search the code (any java class in the Narayana lra submodule) and find the pattern and fix it.
On top of that, your fix provides the same (or similar) wording now. But what if the text of the error message changes? We would rather need to take the message and provide it directly to the `WebApplicationException`. Not to copying the text and hardcoding it to the class.
Something which is here: https://github.com/jbosstm/narayana/blob/master/rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java#L325
What I'm not sure right now is to verify how the `WebApplicationException` is logged at the coordinator if the message could not be logged twice now.

We are happy about you interest in Narayana LRA project. As my explanation could not contain all the details, please, join us at the our gitter channel here: https://gitter.im/jbosstm/community
We can discuss our perspectives.

Plus, excuse me but I'm going to close https://github.com/jbosstm/narayana/pull/1860 which points to 5.11 branch which is a maintenance branch where we do not plan to merge any LRA fixes.

2021-06-21 14:21 UTC, xstefank approved these changes

2021-06-22 07:22 UTC, xstefank commented
Premature approve, dismiss it please. I didn't notice that the scope is bigger.

2021-06-22 07:26 UTC, ochaloup commented
@xstefank thanks for the clarification. I think I do not have permission to dismiss the approval but I'm in contact with @moulalis and we discussed the scope of the issue. I think we are clear that there is needed some more changes to fix the issue (plus the current code change does not compile which needs to be fixed as well).

2021-06-22 07:39 UTC, ochaloup requested changes
Just explicitly marking the PR that it needs some adjustments (details in my comment above)

2021-06-22 16:24 UTC, mmusgrov approved these changes

2021-06-22 16:32 UTC, mmusgrov commented
I also updated the JIRA indicating how to avoid this kind of discrepancy.

2021-06-22 17:27 UTC, mmusgrov commented
I am copying my comment on the issue over here as well:

```
Can we also avoid duplicating the string for the error message, ie populate the exception message using the log message by returning a String from the message. An example is:

@Message(id = 25004, value = "LRA finished with an unexpected status code: %d, coordinator response '%s'")
String error_lraTerminationUnexpectedStatus(int status, String response);
`

2021-06-23 09:32 UTC, mmusgrov commented
@moulalis what changes are you proposing in this PR. The only diff that I can see in the PR (including your recent force pushes) are the addition of a space character and the removal of a new line character. Each time an engineer pushes a new change to a PR it will trigger the consumption of CI resources in our Jenkins installation. Ondra has indicated what needs to be done and pushing commits that remove single white space characters is not a good use of engineering resource.

2021-06-23 09:52 UTC, mmusgrov requested changes
Please refer to [Ondra comment](https://github.com/jbosstm/narayana/pull/1859#issuecomment-865037902) to see what actions need to be done for this PR to qualify as a fix for JBTM-3424.

@moulalis I am adding the "On Hold" label while you decide whether or not you wish to pursue the fix. If you still want to fix it then I will remove the label when you propose a more comprehensive solution.

2021-06-23 10:01 UTC, moulalis commented
> @moulalis what changes are you proposing in this PR. The only diff that I can see in the PR (including your recent force pushes) are the removal of a space character and the removal of a new line character. Each time an engineer pushes a new change to a PR it will trigger the consumption of CI resources in our Jenkins installation. Ondra has indicated what needs to be done and pushing commits that remove single white space characters is not a good use of engineering resources.

@mmusgrov It was my bad, sorry for it, I was checking why build is getting failed, '}' was missing but by any how I was suppose to push other PR and by mistake I did it here. It was all my bad.

2021-06-23 10:03 UTC, mmusgrov commented
@moulalis Ah right okay, understood and fair enough, sorry if I was a bit terse.

2021-06-23 10:03 UTC, moulalis commented
> Please refer to [Ondra comment](https://github.com/jbosstm/narayana/pull/1859#issuecomment-865037902) to see what actions need to be done for this PR to qualify as a fix for JBTM-3424.
> 
> @moulalis I am adding the "On Hold" label while you decide whether or not you wish to pursue the fix. If you still want to fix it then I will remove the label when you propose a more comprehensive solution.

I would be working on this and making the changes as Ondra suggested.

2021-06-23 10:04 UTC, mmusgrov commented
> > Please refer to [Ondra comment](https://github.com/jbosstm/narayana/pull/1859#issuecomment-865037902) to see what actions need to be done for this PR to qualify as a fix for JBTM-3424.
> > @moulalis I am adding the "On Hold" label while you decide whether or not you wish to pursue the fix. If you still want to fix it then I will remove the label when you propose a more comprehensive solution.
> 
> I would be working on this and making the changes as Ondra suggested.

Okay, I will remove the hold label when you are ready with a more comprehensive fix, thanks.

2021-06-29 16:35 UTC, mmusgrov requested changes
@ochaloup please can you also take a look

2021-06-29 16:35 UTC, mmusgrov commented on rts/lra/client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
> -
We don't normally make formatting changes (removing a line) amongst other changes.

2021-06-29 16:35 UTC, mmusgrov commented on rts/lra/client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
> +                String errorMsg = String.format("%s (%s)", logMsg);
Insufficient parameters for format string.

2021-06-29 16:35 UTC, mmusgrov commented on rts/lra/service-base/src/main/java/io/narayana/lra/logging/LraI18nLogger.java
> -
We don't allow formatting changes amongst functional changes (ie a blank line has been removed

2021-06-29 16:35 UTC, mmusgrov commented on rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
> -                    "'getNestedLRAStatus': The LRA is still active.", nestedLraId, lra.getId());
You have missed all of the remaining data in the errMsg

2021-06-29 16:35 UTC, mmusgrov commented on rts/lra/client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
> +            String errorMsg = String.format("%s (%s)", logMsg, e.getClass().getName() + ":" + e.getMessage());
The exception class, `e.getClass().getName()`, should already be reported in the logger call `error_invalidLraIdFormatToConvertToCoordinatorUrl`` .

2021-06-29 16:35 UTC, mmusgrov commented on rts/lra/client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
> +                String errorMsg = String.format("%s (%s)", logMsg);
Insufficient parameters for format string. This mistake is also done elsewhere so I will not repeat this review comment but it needs fixing in all places.

2021-07-05 13:52 UTC, mmusgrov requested changes
There are still a number of change requests needed on this PR.

2021-07-05 13:52 UTC, mmusgrov commented on rts/lra/client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
> +            String errorMsg = String.format("%s (%s:%s %s %s %s (%s:%s) )", logMsg, "Cannot connect to the LRA coordinator", coordinatorUrl,
Incorrect usage of String.format. The syntax is defined in the javadoc for Formatter: https://docs.oracle.com/javase/8/docs/api/java/util/Formatter.html

2021-07-05 13:52 UTC, mmusgrov commented on rts/lra/client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
> +                    errorMsg, uee);
I would keep it simple and just use logMsg here.

2021-07-05 13:52 UTC, mmusgrov commented on rts/lra/client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
> +                throwGenericLRAException(null, response.getStatus(),  errorMsg, null);
I would just use logMsg here.

2021-07-05 13:52 UTC, mmusgrov commented on rts/lra/client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
> +            String errorMsg = String.format("%s", logMsg);
This statement serves no purpose

2021-07-05 13:52 UTC, mmusgrov commented on rts/lra/client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
> +                String errorMsg = String.format("%s", logMsg);
This statement serves no purpose. I notice that you have done this in quite a few places in the PR so I will not mention further examples but it needs fixing.

2021-07-05 13:52 UTC, mmusgrov commented on rts/lra/client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
> +                throw new WebApplicationException(errorMsg,
There is a mismatch here, in other places the exception message and the response to the client are the same text. For consistency I would keep them the same. Similarly in other places in this PR.

2021-07-05 13:52 UTC, mmusgrov commented on rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
> +            LRALogger.logger.error(errMsg);
errMsg is not the same as the i18n log message (error_cannotGetStatusOfNestedLraURI) which it should be.

2021-07-05 13:52 UTC, mmusgrov commented on rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
> +                String errorMsg = String.format("%s (%s)", logMsg, e1.getMessage());
logMsg already contains the error message. Just use logMsg.

2021-07-05 13:52 UTC, mmusgrov commented on rts/lra/coordinator/src/main/java/io/narayana/lra/coordinator/api/Coordinator.java
> +            String errorMsg = String.format("%s (%s)", logMsg, e.getMessage());
logMsg already contains the error message. Just use logMsg.
You have done the same in other places so I will not repeat this comment but it needs changing throughout.

2021-07-05 13:52 UTC, mmusgrov commented on rts/lra/service-base/src/main/java/io/narayana/lra/logging/LraI18nLogger.java
> +import org.jboss.logging.annotations.Cause;
The imports have been rearranged, we disallow formatting changes in PRs.

2021-07-12 14:34 UTC, mmusgrov commented
> Premature approve, dismiss it please. I didn't notice that the scope is bigger.

@xstefank you should have the requisite permissions to dismiss it - it would be setting a precedent if we do it for you.

2021-07-12 14:56 UTC, xstefank commented
@mmusgrov I don't have access to the repo so I don't think I can dismiss reviews.

2021-07-13 07:40 UTC, mmusgrov commented
@xstefank we don't have permission to dismiss your review either so let's just leave it as it is.

2021-07-14 07:27 UTC, moulalis commented
@mmusgrov could you please review, I have moved the latest changes. 
Thanks

2021-07-14 19:22 UTC, mmusgrov commented on rts/lra/service-base/src/main/java/io/narayana/lra/logging/LraI18nLogger.java
> +                                           String coordinatorStatusMsg, int returnStatusCode, String returnStatusMsg);
You should avoid adding white space, I would keep the original spacing.

2021-07-14 19:30 UTC, mmusgrov requested changes
@moulalis Many of my review comments have either not been addressed or have not been responded to. If the author of the PR disagrees with a comment then there needs to be a follow up comment explaining why the change request has not been applied.
 
Also in my original review I pointed out some issues remarking that if a problem was repeated more than once I said I would not comment on all occurrences of the problem but that they all needed to be fixed. Here I am referring a number of examples of `String errorMsg = String.format("%s", logMsg);` which is a statement that serves no purpose.

And the following comment added by @ochaloup has not been responded to:

> ... it would be good to verify how the WebApplicationException is logged at the coordinator, could be the message is logged twice now (not sure)?

2021-07-15 11:09 UTC, moulalis commented
@mmusgrov errorMsg and blank space removed. Thanks

2021-07-16 09:46 UTC, mmusgrov commented
@moulalis I've put this PR on hold while you wait for input from @ochaloup and while you address the summary I provided in my last review.

2021-07-19 08:19 UTC, ochaloup reviewed
To me it seems fine in general.

My point about `WebApplicationException` was that I was afraid if the exception is not logged at filter or at RestEasy level which would mean to log the same message twice or more times. Such behaviour would not seem to me as a nice.
I was thinking that would be good to verify - like via running some testcase what we have in TCK - how the message is logged when `WebApplicationException` is thrown.
@mmusgrov what do you think about having the exception being logged only by RestEasy (if it does so) and not printing errors in cases when the RestEasy does so?

2021-07-19 08:19 UTC, ochaloup commented on rts/lra/service-base/src/main/java/io/narayana/lra/logging/LraI18nLogger.java
> +    String error_lraLeaveUnexpectedStatus(URI lra, int status, String response);
@mmusgrov I understood it in way that we can change the message but we can't change the `I18N` code. When we found the message is not precise we can change it to be comprehensible or better describing the intention. My understanding.

2021-07-19 08:59 UTC, mmusgrov commented
> To me it seems fine in general.
> 
> My point about `WebApplicationException` was that I was afraid if the exception is not logged at filter or at RestEasy level which would mean to log the same message twice or more times. Such behaviour would not seem to me as a nice.
> I was thinking that would be good to verify - like via running some testcase what we have in TCK - how the message is logged when `WebApplicationException` is thrown.
> @mmusgrov what do you think about having the exception being logged only by RestEasy (if it does so) and not printing errors in cases when the RestEasy does so?

So are you suggesting that @moulalis needs to run the TCK (or one of the TCKs tests that throw a WebApplicationException preceded by one of our log messages) and to then verify that there isn't more than one entry in the logs for the same problem.
I didn't quite get your point about RESTEasy logging since the developer would generally just enable LRA logging (and would not enable RESTEasy logging), is that what you meant?

> @mmusgrov I understood it in way that we can change the message but we can't change the I18N code. When we found the message is not precise we can change it to be comprehensible or better describing the intention. My understanding.

Okay, in that case we can accept this one particular change, but in general changing the log messages should be avoided since there is no place where a user may enter the i18n code to find out what it means (I do it by extracting the last 5 characters of the code and then I search the source base). I do have a further general comment about the error messages, if we are going to allow changes to the text then some of them really don't read very well and they could benefit from a rewording - perhaps we could do this before publishing the list of codes along with their meanings.

So @moulalis, I Ondra is saying that you need to run the TCK and verify whether or not any problems are logged twice, is that correct @ochaloup ?
You also need to address the comments that I left in [my last review of this PR](https://github.com/jbosstm/narayana/pull/1859#pullrequestreview-706643099) .

2021-07-19 13:28 UTC, ochaloup commented
```
So are you suggesting that @moulalis needs to run the TCK (or one of the TCKs tests that throw a WebApplicationException preceded by one of our log messages) and to then verify that there isn't more than one entry in the logs for the same problem.
I didn't quite get your point about RESTEasy logging since the developer would generally just enable LRA logging (and would not enable RESTEasy logging), is that what you meant?

So @moulalis, Ondra is saying that you need to run the TCK and verify whether or not any problems are logged twice, is that correct @ochaloup ?
```

@mmusgrov yest, that' so. My perspective is that it would be good to not log the same problem twice. It would be good to verify it. The TCK or Narayana LRA integration test could help to verify the behaviour.
I mentioned RESTEAsy as it's the framework which manages the processing and the web exceptions are processed there and transformed to error codes. That's why I mentioned the RESTEasy and that it would be the place where the errors are printed (again).

2021-07-19 17:04 UTC, moulalis commented
> So @moulalis, I Ondra is saying that you need to run the TCK and verify whether or not any problems are logged twice, is that correct @ochaloup ?
@ochaloup could you please run TCK for me as you suggested.

> You also need to address the comments that I left in [my last review of this PR](https://github.com/jbosstm/narayana/pull/1859#pullrequestreview-706643099) .
@mmusgrov I've already fixed and pushed my changes.

2021-07-19 20:27 UTC, ochaloup commented
@moulalis 
What I meant was that I can help you to run the TCK on your machine. What you need is to first build Narayana codebase and then run the TCKs. Like

```
./build.sh install -Pcommunity -DskipTests
cd rts/lra/test/
mvn clean verify -Parq -pl tck
```

Or you can use nightly tests of the Narayana from our CI (Red Hat VPN access is needed though) here: http://narayanaci1.eng.hst.ams2.redhat.com/job/narayana/PROFILE=LRA,jdk=jdk8.latest,label=linux/

2021-07-20 03:10 UTC, moulalis commented
> @moulalis
> What I meant was that I can help you to run the TCK on your machine. What you need is to first build Narayana codebase and then run the TCKs. Like
> 
> ```
> ./build.sh install -Pcommunity -DskipTests
> cd rts/lra/test/
> mvn clean verify -Parq -pl tck
> ```
> 
> Or you can use nightly tests of the Narayana from our CI (Red Hat VPN access is needed though) here: http://narayanaci1.eng.hst.ams2.redhat.com/job/narayana/PROFILE=LRA,jdk=jdk8.latest,label=linux/

Thanks @ochaloup I was trying say about CI from Narayana. I will try it in locally and check.

2021-07-20 14:38 UTC, ochaloup commented
@moulalis @mmusgrov we discussed the behaviour with @moulalis and I agree that TCKs shows there should be no double logging of the event when `WebApplicationException` is thrown. I'm fine about my objection.
Thanks @moulalis for investigation.

2021-07-20 14:39 UTC, ochaloup approved these changes
The fix seems fine to me now.

2021-07-20 15:44 UTC, moulalis commented
> @moulalis @mmusgrov we discussed the behaviour with @moulalis and I agree that TCKs shows there should be no double logging of the event when `WebApplicationException` is thrown. I'm fine about my objection.
> Thanks @moulalis for investigation.

Thanks @ochaloup attaching log.txt for 
[log.txt](https://github.com/jbosstm/narayana/files/6849624/log.txt)
reference.

2021-07-26 11:08 UTC, ochaloup commented
@moulalis thanks for your adjustments.
Just wanted to clarify that I agree with request put by Mike. For merging this PR those have to be fixed first.

2021-07-26 14:33 UTC, moulalis commented
> @moulalis thanks for your adjustments.
> Just wanted to clarify that I agree with request put by Mike. For merging this PR those have to be fixed first.

@ochaloup I've already fixed those. @mmusgrov I've double-checked might be I am not able to find which part is missing, could you please review once and let me know.
Thanks.

2021-07-26 16:20 UTC, mmusgrov commented
https://github.com/jbosstm/narayana/pull/1859/files#r663920421
https://github.com/jbosstm/narayana/pull/1859/files#r663933880
https://github.com/jbosstm/narayana/pull/1859/files#r663945091

These three review comments either need to be acted upon or you need to justify why they are not applicable. It's fine to say that the reviewers comments are invalid but it's not okay to ignore them.

2021-07-26 16:37 UTC, mmusgrov commented on rts/lra/client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
> +                throw new WebApplicationException(errorMsg,
Note that ,although you appear to be adding extra information (uri.toASCIIString()) to the exception message, the uri is actually the same as the lraId which has already been added to logMsg, ie it adds no value. Therefore using the value in the variable logMsg is sufficient.

And I don't recall (without checking) what I was referring to when I said `Similarly in other places in this PR` so you should perform a quick sanity check to verify you haven't done something similar elsewhere.

2021-07-27 05:26 UTC, moulalis commented
> https://github.com/jbosstm/narayana/pull/1859/files#r663920421
> https://github.com/jbosstm/narayana/pull/1859/files#r663933880
> https://github.com/jbosstm/narayana/pull/1859/files#r663945091
> 
> These three review comments either need to be acted upon or you need to justify why they are not applicable. It's fine to say that the reviewers comments are invalid but it's not okay to ignore them.

@mmusgrov Changes updated, for https://github.com/jbosstm/narayana/pull/1859/files#r663920421 I've asked if still required to use logMsg, didn't repeat the same to other two. Its seems like ignore all other message and make only logMsg consistent wherever logged. I made the changes as expected. 
Thanks

2021-07-27 08:46 UTC, mmusgrov commented on rts/lra/client/src/main/java/io/narayana/lra/client/NarayanaLRAClient.java
> +                throw new WebApplicationException(logMsg,
Part of what we discussed on this LRA is that the message in the exception response needs to correspond to the i18n log message. Here you are setting the exception message to be the same as the log message but you are then passing something different back to the caller, if you check the [javadoc for this exception](https://docs.oracle.com/javaee/7/api/javax/ws/rs/WebApplicationException.html#WebApplicationException-java.lang.String-javax.ws.rs.core.Response-) you should see what I mean.

I also said that the value in the uri variable is the same as the value in the lraId so the value in the response entity adds nothing, so this exception does not follow this advice. The intention is for the log message and the exception response to be consistent - you have followed this advice in other parts of this PR but we need consistency across the whole of the PR.

This looks like the only remaining issue on the PR so we are almost there!

2021-07-27 10:54 UTC, moulalis commented
@mmusgrov Changes updated.
Thanks.

2021-07-27 15:01 UTC, mmusgrov approved these changes
The changes look good, I will merge them.

2021-07-27 15:02 UTC, mmusgrov commented
I think the earlier approval from @ochaloup was contingent on resolving the other reviewer's comments which have now been fully addressed so I will merge this one.

2021-07-27 15:03 UTC, merged