JBTM-3510 Replace new Integer(int) with valueOf(int) and also for oth…
jbosstm/narayana pull request #1874
Opened 2021-07-02 19:57 UTC by RanabirChakraborty

Issue: https://issues.redhat.com/browse/JBTM-3510

2021-07-03 16:05 UTC, RanabirChakraborty commented
TOMCAT, JACOCO, LRA config got failed for jdk8, tho' I'm not sure but looking at the errors I don't think it was affected by the PR changes.

2021-07-05 11:52 UTC, mmusgrov requested changes
There are quite a few examples where the boxing and unboxing are unnecessary.

2021-07-05 11:52 UTC, mmusgrov commented on ArjunaJTS/orbportability/classes/com/arjuna/orbportability/common/ant/IDLCompiler.java
> +        _debugOn = Boolean.valueOf(debug).booleanValue();
You don't need to unbox the boolean value, ie `_debugOn = Boolean.valueOf(debug)` is sufficient.
Similarly elsewhere in this PR.

Also `Boolean.valueOf(debug)` assigns a boxed value to the primitive `_debugOn` so incurs unboxing.

So to summarise the best approach is to just do `_debugOn = Boolean.parseBoolean(debug);` 

Similarly elsewhere in this PR (ie I won't repeat the same comment).

2021-07-05 11:52 UTC, mmusgrov commented on STM/src/main/java/org/jboss/stm/internal/proxy/LockManagerProxy.java
> +                afield.set(_theObject, Boolean.valueOf(os.unpackBoolean()));
You don't need to box the value before passing it to `afield.set`. So `afield.set(_theObject, os.unpackBoolean());` is sufficient. Similarly for the other changes in this routine and in other places where the same unnecessary boxing has been done in this PR.

2021-07-05 11:52 UTC, mmusgrov commented on STM/src/test/java/org/jboss/stm/internal/proxy/LockManagerProxyUnitTest.java
> +            _isState = Double.valueOf(1.234);
You don't need to box the primitive and then assign it to a primitive, ie `_isState = 1.234;` is sufficient. Similarly where the same has been done elsewhere in this PR.

2021-07-05 11:52 UTC, mmusgrov commented on XTS/WS-C/dev/src/com/arjuna/wsc11/messaging/ActivationCoordinatorProcessorImpl.java
> +                    final Long expires = (expiresElement == null ? null : Long.valueOf(expiresElement.getValue())) ;
Unnecessary boxing, `expiresElement.getValue()` is sufficient. Similarly elsewhere in this PR.

2021-07-05 11:52 UTC, mmusgrov commented on XTS/WSTX/classes/com/arjuna/mwlabs/wst11/at/remote/UserTransactionImple.java
> +            final Long expires = (timeout > 0 ? Long.valueOf(timeout) : null) ;
Unnecessary boxing, use `(long) timeout` instead. Similarly elsewhere in this PR.

2021-07-05 11:52 UTC, mmusgrov commented on XTS/localjunit/WSTFSC07-interop/src/main/java/com/jboss/transaction/wstf/test/TestServlet.java
> +        session.setAttribute(TestConstants.ATTRIBUTE_LOG_COUNT, Integer.valueOf(logCount)) ;
Unnecessary boxing (similarly elsewhere in this PR).

2021-07-05 11:52 UTC, mmusgrov commented on XTS/localjunit/unit/src/test/java/com/arjuna/wsc/tests/arq/ActivationTest.java
> +        final Long expires = Long.valueOf(123456L) ;
Unecessary boxing

2021-07-09 09:48 UTC, RanabirChakraborty commented
@mmusgrov did the changes accordingly. Can you please review this once :)

2021-07-09 10:10 UTC, mmusgrov approved these changes
@RanabirChakraborty thanks for the fixes. The PR looks good and I will merge it.

2021-07-09 10:10 UTC, merged

2021-07-09 10:17 UTC, RanabirChakraborty commented
Thanks! :)