[JBTM-3526] Split failsafe reports based on running arq profile
jbosstm/narayana pull request #1901
Opened 2021-09-02 12:07 UTC by jmfinelli

This PR addresses [JBTM-3526](https://issues.redhat.com/browse/JBTM-3526)

!MAIN !CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_JACORB !QA_JTS_JDKORB !QA_JTS_OPENJDKORB !PERF LRA NO_WIN !DB_TESTS !mysql !db2 !postgres !oracle

2021-09-02 15:11 UTC, mmusgrov requested changes
The CI run did not produce any files called `failsafe-summary.xml` which it should have done.

2021-09-02 15:23 UTC, jmfinelli commented
> The CI run did not produce any files called `failsafe-summary.xml` which it should have done.

@mmusgrov That's not a problem of this PR but of our CI. As you can see in the configuration of the job, the `Post-build Actions` saves all files in `**/target/*failsafe-reports*/**`. I have updated this PR to try to match that regex pattern :crossed_fingers:

2021-09-02 15:25 UTC, ochaloup approved these changes

2021-09-03 16:01 UTC, mmusgrov commented
> > The CI run did not produce any files called `failsafe-summary.xml` which it should have done.
> 
> @mmusgrov That's not a problem of this PR but of our CI. As you can see in the configuration of the job, the `Post-build Actions` saves all files in `**/target/*failsafe-reports*/**`. I have updated this PR to try to match that regex pattern

The last run looks good.

2021-09-03 16:01 UTC, mmusgrov approved these changes

2021-09-03 16:03 UTC, merged