[JBTM-3374] afterLRA method is repeatedly called with simple LRA reso…
jbosstm/narayana pull request #1976
Opened 2022-05-27 13:59 UTC by marcosgopen

[[JBTM-3374]](https://issues.redhat.com/browse/JBTM-3374)  afterLRA method is repeatedly called with simple LRA resource

adding AfterLRA in filter check.
adding test.

CORE TOMCAT AS_TESTS RTS JACOCO XTS QA_JTA QA_JTS_JACORB QA_JTS_JDKORB QA_JTS_OPENJDKORB PERF LRA !DB_TESTS !mysql !db2 !postgres !oracle

2022-05-30 15:41 UTC, mmusgrov requested changes
The PR looks great thanks, I only had a couple of minor change requests.
The CI test failures are expected since the integration tests that use WildFly do not work with Java 8 (since WildFly doesn't support it).

2022-05-30 15:41 UTC, mmusgrov commented on rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/resource/LRAParticipantAfterLRA.java
> + * Copyright 2020, Red Hat, Inc., and individual contributors
Wrong date. BTW there is a [new copyright statement](https://github.com/jbosstm/narayana/blob/master/CONTRIBUTING.md#legal)

2022-05-30 15:41 UTC, mmusgrov commented on rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/LRAParticipantAfterLRAIT.java
> + * Copyright 2019, Red Hat, Inc., and individual contributors
Wrong date. BTW there is a [new copyright statement](https://github.com/jbosstm/narayana/blob/master/CONTRIBUTING.md#legal)

2022-05-31 07:59 UTC, marcosgopen commented
Thanks @mmusgrov for your review! I have just updated the commit in order to have the narayana header in the files and the logger.

2022-05-31 08:20 UTC, mmusgrov approved these changes
The PR looks good and is ready to be merged, thanks.

2022-05-31 08:20 UTC, mmusgrov commented on rts/lra/test/basic/src/test/java/io/narayana/lra/arquillian/resource/LRAParticipantAfterLRA.java
> +        return Response.ok().entity(lraId + "\n").build();
Remark: adding a newlline means the caller must parse the response. However, if another engineer wants to reuse your participant then he can remove the newline.

2022-06-03 10:24 UTC, merged