More jbtm 3590 openjdkorb
jbosstm/narayana pull request #1995
Opened 2022-07-01 11:48 UTC by tomjenkinson

JEP-320 and also consolidate the versions of JacORB https://issues.redhat.com/browse/JBTM-3590

CORE !TOMCAT AS_TESTS !RTS !JACOCO !XTS !QA_JTA QA_JTS_JACORB QA_JTS_JDKORB QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS mysql db2 postgres oracle

2022-07-01 13:02 UTC, tomjenkinson commented
CORE profile looked to be out of memory

2022-07-05 09:11 UTC, jmfinelli requested changes
I put this comment here but it is not strictly related to this modification.

I think that `idlj-idl` and `idlj-idl-tests` maven modules can be removed from Narayana. In other words, I think we can completely remove `idlj` and `idlj-tests` from `idlj-idl-parent` and move `idlj-openjdk` to `idl` (where the other idls [e.g. `jacorb-idl` and `ibmorb-idl]` are).
It seems that `idlj-idl` and `idlj-idl-tests` are just a repacking of `openjdk-idl`. Plus, AFAICT, `idlj-idl-parent` was there to logically group `idlj` (idl to java in JDK) and `idlj-openjdk` (idl to java in (our fork) of openJDK).
The main consequence of refactoring idl will be that all maven modules depending on `idlj-idl` and `idlj-idl-tests` should change their dependencies to include `openjdk-idl` (and its `test-jar`)

2022-07-05 09:49 UTC, tomjenkinson commented on scripts/hudson/narayana.sh
> +  [ $ok1 = 0 -a $ok3 = 0 -a $ok4 = 0 ] || fatal "some qa tests failed"
I was just making the minimal change really, I think it could be done what you said though

2022-07-05 09:52 UTC, tomjenkinson commented
I think your point about the refactor of `idlj-openjdk` could be done after merging this as a separate JBTM. 

I haven't reviewed the points about removing `idlj-idl` and `idlj-idl-tests` but I do think that should be done if possible in this PR so I will put this on `Hold` while that is further reviewed.

2022-07-05 12:02 UTC, tomjenkinson commented
@jmfinelli I hope that https://github.com/jbosstm/narayana/pull/1995/commits/954604f2624fc43d9ac033070cf5cb27c8a278ea will be helpful to address the points you raised about the old modules

2022-07-05 13:45 UTC, jmfinelli commented on scripts/hudson/narayana.sh
> +  [ $ok1 = 0 -a $ok3 = 0 -a $ok4 = 0 ] || fatal "some qa tests failed"
What about this one? If you do not want to modify it now, I already have the changes in my pr to remove JacORB

2022-07-05 14:34 UTC, tomjenkinson commented on scripts/hudson/narayana.sh
> +  [ $ok1 = 0 -a $ok3 = 0 -a $ok4 = 0 ] || fatal "some qa tests failed"
I don't plan on changing this here but if you would like to change something in this area then I think changing to more descriptive names of what result is being stored could be helpful

2022-07-06 08:51 UTC, tomjenkinson commented
(I have just removed `Hold` - I removed the `idlj-idl` and `idlj-idl-tests` modules, thanks for spotting that @jmfinelli!)

2022-07-06 09:44 UTC, jmfinelli approved these changes
LGTM! Thanks Tom

2022-07-06 09:45 UTC, merged