[JBTM-3645] osbTypeMap is now initialised only once
jbosstm/narayana pull request #2008
Opened 2022-07-18 13:25 UTC by jmfinelli

Addresses [JBTM-3645](https://issues.redhat.com/browse/JBTM-3645)

CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS !mysql !db2 !postgres !oracle

2022-07-20 12:43 UTC, jmfinelli commented
CORE failed because of the change of API in `ObjStoreBrowser` (which this JIRA/PR is all about). Should I deprecate the constructors of `ObjStoreBrowser` and remove them when we are sure that the community is aware of this modification?

2022-07-20 14:04 UTC, mmusgrov reviewed
I added a comment to the issue indicating that making an API change for very little benefit is questionable - the whole package is already marked as `Deprecated` so there is no requirement to support ad hoc usage of the instrumentation. I also pointed out the knock on effect of breaking existing management applications that use the instrumentation.

2022-07-22 13:45 UTC, mmusgrov commented
@jmfinelli I've added the hold label until you've decided how you wish to proceed. As discussed elsewhere this is a change that breaks certain JMX/management expectations and is a change that we do not want.

2022-07-22 13:58 UTC, jmfinelli commented
That's fine to me. Maybe, let's just add a comment to the javadoc of `ObjStoreBrowser` to make it clear that, by design, there must not be two instances of `ObjStoreBrowser` around (basically, developers should consider `ObjStoreBrowser` as a singleton class).

I would also add that we should consider when it is a good time to move `ObjStoreBrowser` into an internal package (maybe next major release?) and add it to our schedule.

I will copy this comment to the related JIRA to keep track of this conversation. Thanks Michael :-)

2022-07-26 16:02 UTC, mmusgrov requested changes
Just a couple of typos but otherwise okay.

2022-07-26 16:02 UTC, mmusgrov commented on ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/osb/mbean/ObjStoreBrowser.java
> +     * are created, they will interere with each other.</p>
/will interere/may interfere/

2022-07-26 16:50 UTC, jmfinelli commented on ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/osb/mbean/ObjStoreBrowser.java
> +     * are created, they will interere with each other.</p>
Thanks Michael. Corrected +1

2022-07-27 12:04 UTC, mmusgrov approved these changes

2022-07-27 14:15 UTC, merged