JBTM-3658 Remove LRA coordinator Quarkus module
jbosstm/narayana pull request #2033
Opened 2022-08-16 09:13 UTC by xstefank

As it was moved to a separate repository.

https://issues.redhat.com/browse/JBTM-3658

!CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERF LRA !DB_TESTS !MySQL !db2 !postgres !oracle

2022-08-30 08:13 UTC, mmusgrov reviewed
How does this PR resolve the related topic that we discussed on zulip (https://narayana.zulipchat.com/#narrow/stream/323715-developers/topic/How.20to.20run.20an.20LRA.20Coordinator.20using.20Quarkus): there has been no progress on that topic for two weeks.

2022-08-31 14:38 UTC, mmusgrov commented
I'm holding this one pending resolution of my last comment and also pending the work on the quickstart repo which has a reliance on this module.

2022-11-10 16:19 UTC, jmfinelli requested changes

2022-11-10 16:19 UTC, jmfinelli commented on rts/lra/test/pom.xml
>      <lra.coordinator.port>8080</lra.coordinator.port>
I think that we can remove the properties from line 39 to 44, WDYT?

2022-11-10 16:19 UTC, jmfinelli commented on rts/lra/test/pom.xml
> +    <lra.participant.xml.filename>lra-participant.xml</lra.participant.xml.filename>
Why have you moved this here? This property is only used in the profile `arq`

2022-11-10 16:19 UTC, jmfinelli commented on rts/lra/test/pom.xml
> +    <wildfly.trace.logging.cli.script>${project.basedir}/../wildfly-trace-logging.cli</wildfly.trace.logging.cli.script>
Why have you moved this here? If I understand correctly, this property is only used in the profile `trace.lra`

2022-11-11 17:17 UTC, mmusgrov requested changes
The changes that remove the `coordinator-quarkus` module look good.

But the PR contain a lot of other changes relating to testing on wildfly that are unrelated - ie it's not clear to me how those relate to the issue description. Would it be possible to raise those changes in a separate PR so that they can be reviewed independently.

I am going to remove the Hold label while we discuss this PR and add the `Urgent` label since we need this PR for the next release of Narayana.

2022-11-11 20:18 UTC, mmusgrov commented
I removed the urgent label since the PR marco referenced means that we just need to disable the deployment of the `lra-coordinator-quarkus` artifact. Then we can avoid issues with deploying the same artifact as the one deployed by the `https://github.com/jbosstm/lra-coordinator-quarkus` repository.

2022-11-16 15:35 UTC, xstefank commented
Still on PTO but I'll fix this if it's urgent. @mmusgrov the test changes are related to the move to the WFLY deployed coordinator where we still passed for instance logging info for the quarkus which wouldn't work. So @mmusgrov and @jmfinelli should I clear this PR to only remove the module and we will clean up testsuite in follow-up?

2022-11-16 15:43 UTC, marcosgopen commented
Thanks @xstefank for your answer! Michael removed the urgent label so we can talk about it when you will be back from PTO.
Thanks again for your PR!

2022-11-21 15:33 UTC, jmfinelli approved these changes
LGTM! Thank you very much @xstefank !

2022-11-21 23:19 UTC, mmusgrov approved these changes
Thanks Martin for separating out the commits. I think this one can now be merged.

2022-11-21 23:20 UTC, merged