Jbtm 3588 common
jbosstm/narayana pull request #2036
Opened 2022-08-30 15:40 UTC by jmfinelli

Initial work on [JBTM-3588](https://issues.redhat.com/browse/JBTM-3588)

JDK11 JDK17 CORE !TOMCAT !AS_TESTS !RTS !JACOCO !XTS !QA_JTA !QA_JTS_OPENJDKORB !PERF !LRA !DB_TESTS !mysql !db2 !postgres !oracle

2022-08-30 17:01 UTC, jmfinelli commented
@mmusgrov, could you please double check that I have activated all needed testing axes?

2022-08-31 15:16 UTC, mmusgrov requested changes
This PR does not fully resolve issue JBTM-3588. If your plan is for us to fix JBTM-3588 in stages then we need to have multiple issues linked to JBTM-3588.

This PR contains a mix of whitespace clean up, pom sorting and some things related to the javax -> jakarta transition. The resolution for JBTM-3588 is such a big change that it needs to focus only on the transformation and not on miscellaneous unrelated additional code updates.

I assume this PR is preparing the way for JBTM-3588 but does not actually address the task and as such you need to a separate JBTM for it.

2022-09-01 08:33 UTC, jmfinelli commented on common/pom.xml
> +            <arg>-Aorg.jboss.logging.tools.addGeneratedAnnotation=false</arg>
> This PR does not fully resolve issue JBTM-3588. If your plan is for us to fix JBTM-3588 in stages then we need to have multiple issues linked to JBTM-3588.

Yes, I planned to use JBTM-3588 to submit multiple PRs (migrating individual modules). Your suggestion to create and use subtasks to track JBTM-3588 sounds better though. As you have a clearer picture of what modules need to be migrated to jakarta, could you please create the initial subtasks for JBTM-3588? (of course, we can create new ones as we go ahead with this work) 

> This PR contains a mix of whitespace clean up, pom sorting and some things related to the javax -> jakarta transition. The resolution for JBTM-3588 is such a big change that it needs to focus only on the transformation and not on miscellaneous unrelated additional code updates.

No problem for me, I can strip off the commits related to SortPom and raise individual PRs later (i.e. after JBTM-3588 is completed)

> I assume this PR is preparing the way for JBTM-3588 but does not actually address the task and as such you need to a separate JBTM for it.

Please, refer to my previous message about subtasks

2022-09-01 08:33 UTC, jmfinelli commented
> This PR does not fully resolve issue JBTM-3588. If your plan is for us to fix JBTM-3588 in stages then we need to have multiple issues linked to JBTM-3588.

Yes, I planned to use JBTM-3588 to submit multiple PRs (migrating individual modules). Your suggestion to create and use subtasks to track JBTM-3588 sounds better though. As you have a clearer picture of what modules need to be migrated to jakarta, could you please create the initial subtasks for JBTM-3588? (of course, we can create new ones as we go ahead with this work) 

> This PR contains a mix of whitespace clean up, pom sorting and some things related to the javax -> jakarta transition. The resolution for JBTM-3588 is such a big change that it needs to focus only on the transformation and not on miscellaneous unrelated additional code updates.

No problem for me, I can strip off the commits related to SortPom and raise individual PRs later (i.e. after JBTM-3588 is completed)

> I assume this PR is preparing the way for JBTM-3588 but does not actually address the task and as such you need to a separate JBTM for it.

Please, refer to my previous message about subtasks

2022-09-01 08:36 UTC, jmfinelli commented on common/pom.xml
> +            <arg>-Aorg.jboss.logging.tools.addGeneratedAnnotation=false</arg>
Already done. So far, it seems there is not any plan to move it to jakarta (the only part that should be migrated is the `Generated` annotation, which is automatically applied to generated classes -> disabling this feature [i.e. using `Generated`] removes the problem)

2022-09-01 14:24 UTC, jmfinelli commented
I'll close this in favour of #2037

2022-09-01 14:24 UTC, closed without merging