comment out automatic website update
jbosstm/narayana pull request #2155
Opened 2023-08-21 16:15 UTC by marcosgopen

This PR disables automatic update of the website source.
A new script will follow for the new website.

NO_TESTS

2023-08-22 16:53 UTC, mmusgrov requested changes
Instead of simply commenting out those targets why not delete them but replace the comment
`<!-- Build web page and push to jboss.org -->` with `We no longer build web pages, nor push to the file server` perhaps adding some text indication of how the release coordinator should perform the equivalent step.

We have a record of the deleted lines in github and the extra comment I've suggested will be a prompt to the reader to look back over the git history to see how we used to do it.

2023-08-23 08:19 UTC, marcosgopen commented
> Instead of simply commenting out those targets why not delete them but replace the comment `<!-- Build web page and push to jboss.org -->` with `We no longer build web pages, nor push to the file server` perhaps adding some text indication of how the release coordinator should perform the equivalent step.
> 
> We have a record of the deleted lines in github and the extra comment I've suggested will be a prompt to the reader to look back over the git history to see how we used to do it.

Maybe I was unclear with this PR. I would like to comment out these lines because I am currently manually managing the update of the website. I will create a PR replacing these commented out lines with proper scripts needed to automatically build and push/update the website.

2023-08-23 08:24 UTC, marcosgopen commented
> Instead of simply commenting out those targets why not delete them but replace the comment `<!-- Build web page and push to jboss.org -->` with `We no longer build web pages, nor push to the file server` perhaps adding some text indication of how the release coordinator should perform the equivalent step.
> 
> We have a record of the deleted lines in github and the extra comment I've suggested will be a prompt to the reader to look back over the git history to see how we used to do it.

Ok, I will change that as you suggested.

2023-08-24 10:02 UTC, mmusgrov approved these changes

2023-08-24 10:07 UTC, merged