JBTM-2880 don't use printStackTrace in non-test code
jbosstm/narayana pull request #2254
Opened 2024-05-29 14:53 UTC by mmusgrov

https://issues.redhat.com/browse/JBTM-2880

CORE TOMCAT AS_TESTS RTS JACOCO XTS QA_JTA QA_JTS_OPENJDKORB PERFORMANCE LRA DB_TESTS mysql db2 postgres oracle !JDK17

Don't need to validate against both jdk's, hence !JDK17

2024-05-29 15:03 UTC, mmusgrov commented on ArjunaJTA/jdbc/tests/classes/com/hp/mwtests/ts/jdbc/basic/ConnectionImpleTest.java
> +//        when(xaConnection.getXAResource()).thenReturn(xaResource);
I will remove these after the current CI test run finishes

2024-05-30 08:47 UTC, marcosgopen requested changes
Thank you @mmusgrov for your PR. I noticed you haven't updated all classes from 'narayana/ArjunaCore/arjuna/classes/com/arjuna/ats' (only narayana/ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/StateManger.java has been updated). e.g. https://github.com/jbosstm/narayana/blob/main/ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/coordinator/BasicAction.java#L2110-L2112

2024-05-30 16:08 UTC, marcosgopen commented
I am sorry @mmusgrov, I think you are still missing 3 classes: see https://github.com/jbosstm/narayana/blob/main/ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/log/LogBrowser.java#L190, https://github.com/jbosstm/narayana/blob/main/ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/stats/TxPerfGraph.java#L171 and https://github.com/jbosstm/narayana/blob/main/ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/OTM.java#L354
It might be a 'search' misbehaviour in the IDE (maybe because of some closed projects).
Looking at the code I found also "System.err.println(e);" (e.g. https://github.com/jbosstm/narayana/blob/main/ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/OTM.java#L360) Do you think it might be replaced by a log too?

2024-05-30 16:14 UTC, marcosgopen approved these changes

2024-05-30 19:34 UTC, mmusgrov commented
> Thanks @mmusgrov! I approve the PR. Looking at the code I found also some "System.err.println(e);" occurrencies (e.g. https://github.com/jbosstm/narayana/blob/main/ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/OTM.java#L360) Do you think it might be replaced by a log too?

I deliberately skipped OTM.java because it is a Swing app (used for window-based applications) and uses standard out and standard err and users would not necessarily wish to consult a logging framework when running the GUI.

2024-05-31 10:41 UTC, marcosgopen commented
> > Thanks @mmusgrov! I approve the PR. Looking at the code I found also some "System.err.println(e);" occurrencies (e.g. https://github.com/jbosstm/narayana/blob/main/ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/tools/OTM.java#L360) Do you think it might be replaced by a log too?
> 
> I deliberately skipped OTM.java because it is a Swing app (used for window-based applications) and uses standard out and standard err and users would not necessarily wish to consult a logging framework when running the GUI.

Ok, I see. Thanks for the clarification.

2024-05-31 14:24 UTC, graben commented on ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/logging/arjunaI18NLogger.java
> +	void unexpected_excepton(@Cause() Throwable arg0);
Hi @mmusgrov, looks like a little typo in unexpected_except(i)on. :)

2024-06-04 16:00 UTC, merged