Define how to identify that a change must be in a major version and c…
jbosstm/narayana pull request #2269
Opened 2024-07-01 15:44 UTC by tomjenkinson

NO_TEST

(has some relation to https://issues.redhat.com/browse/JBTM-3856)

2024-07-01 15:47 UTC, marcosgopen approved these changes
Thanks @tomjenkinson for your PR

2024-07-02 13:55 UTC, jmfinelli approved these changes

2024-07-03 17:14 UTC, mmusgrov requested changes
The text needs to be in section that covers JIRA, ie https://github.com/jbosstm/narayana/blob/main/CONTRIBUTING.md#update-the-issue-with-the-correct-release-information

Also the text that refers to `8.later` should be `8.next` since the `next` suffix is referring to the next release whereas the `later` suffix is saying that we don't know which release it is targeted for except that it will be in some 8.x version but not necessarily the next one.

2024-07-04 08:29 UTC, tomjenkinson commented
@mmusgrov I think I responded to both of your requests. Thank you for your review and observations.

2024-07-04 13:39 UTC, mmusgrov approved these changes
I'm approving because I know what the process is already but I think we should ask someone who is not familiar with the process to review this one, not sure who we'd ask though. But since I've approved it you are at liberty to merge it.

2024-07-04 13:39 UTC, mmusgrov commented on CONTRIBUTING.md
> +If the change would result in behaviour in Narayana that is incompatible with the current release stream for Narayana, then the relevant JIRA issue `Fix Version/s` must be set to the `<version+1>.nex
Remark if I read this example literally then the fix version would need to be set to `8.0.3.Final-SNAPSHOT` but I think contributors will understand your intention.

2024-07-04 13:39 UTC, mmusgrov commented on CONTRIBUTING.md
> +2. If the `Fix Version/s` is not set to `<version+1>.next`, set the `Fix Version/s` field to `<version>.next`
Remark: So this awkward text is accommodating the case where the issue is a blocker.

2024-07-04 13:54 UTC, merged